- .circleci/config.yml
- .rubocop.yml
- app/controllers/conservation_records_controller.rb
- app/models/conservation_record.rb
I renamed the CircleCI config file and made a couple of tweaks to the YAML file, we're now able to run builds on Travis.
fixes: #20
> Rename the CircleCI config file.

- app/views/shared/_navigation.html.erb
We need this to make the app a little more useable on Lucy so the preservation department can test out the app.
> Add links to nav bar.

- .rubocop.yml
- app/assets/javascripts/search.coffee
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/search.scss
- app/controllers/search_controller.rb
- app/helpers/search_helper.rb
- app/views/search/help.html.erb
- app/views/search/results.html.erb
- app/views/shared/_navigation.html.erb
- config/routes.rb
- spec/controllers/search_controller_spec.rb
Adds very basic search functionality.  Currently it is possible to look up records in the following ways:
- Database ID
- Item Record Number
- Using an SQL like statement on the title
> #13 Adds basic search functionality.

- app/views/conservation_records/show.html.erb
> #33 Opens conservation worksheet in a new tab.

- app/controllers/conservation_records_controller.rb
- app/helpers/application_helper.rb
- app/views/conservation_records/_form.html.erb
- app/views/conservation_records/conservation_worksheet.html.erb
- app/views/conservation_records/show.html.erb
- db/departments.txt
- db/migrate/20190726205510_modify_department_on_conservation_records.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/conservation_records_controller_spec.rb
- spec/controllers/search_controller_spec.rb
- spec/factories/conservation_records.rb
- spec/rails_helper.rb
- spec/views/conservation_records/conservation_worksheet.erb_spec.rb
- spec/views/conservation_records/edit.html.erb_spec.rb
- spec/views/conservation_records/new.html.erb_spec.rb
- spec/views/conservation_records/show.html.erb_spec.rb
fixes: #11;
Modified application and test code to make department field a drop down rather than a text input.
> Changes Department to Dropdown Menu

- db/seeds.rb
fixes: #58 
Each seed user now has one of the three roles.
> Add roles to users created using seeds file.

- .rubocop.yml
- app/assets/javascripts/treatment_reports.coffee
- app/assets/stylesheets/treatment_reports.scss
- app/controllers/conservation_records_controller.rb
- app/controllers/treatment_reports_controller.rb
- app/helpers/treatment_reports_helper.rb
- app/models/conservation_record.rb
- app/models/treatment_report.rb
- app/views/conservation_records/show.html.erb
- config/routes.rb
- db/housing.txt
- db/migrate/20191029113942_create_treatment_reports.rb
- db/migrate/20191029142418_add_conservation_record_to_treatment_reports.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/conservation_records_controller_spec.rb
- spec/controllers/treatment_reports_controller_spec.rb
- spec/factories/treatment_reports.rb
- spec/helpers/treatment_reports_helper_spec.rb
- spec/models/treatment_report_spec.rb
- spec/views/conservation_records/show.html.erb_spec.rb
closes #31 ;
Adds the 1 to 1 relation between the conservation report and the treatment report, set up forms.  I still need to write some tests for this though.
> Add Treatment Report Functionality

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_form.html.erb
- db/migrate/20200124174713_add_account_active_to_user.rb
- db/schema.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/views/shared/_navigation.html.erb_spec.rb
- spec/views/users/edit.html.erb_spec.rb
Resolves #57 
Add ability and controls for admin to enable and disable user accounts.
> admin can enable and disable users

- .rubocop.yml
- app/controllers/cost_return_reports_controller.rb
- app/helpers/external_repair_records_helper.rb
- app/helpers/in_house_repair_records_helper.rb
- app/views/conservation_records/show.html.erb
- app/views/conservation_records/treatment_report_pdf.html.erb
- db/schema.rb
- spec/helpers/external_repair_records_helper_spec.rb
- spec/helpers/in_house_repair_records_helper_spec.rb
fixes: #75 
The internal and external repairs are now numbered on the web view and the PDF report.  The change itself was in the helper.
> #75 Number Internal and External Repairs

- Dockerfile
- README.md
- scripts/wkhtmltopdf.sh
This is a new branch with updated docker file
> New docker branch with updated dockerfile

- .gitignore
- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/assets/javascripts/activity.coffee
- app/assets/stylesheets/activity.scss
- app/controllers/activity_controller.rb
- app/controllers/application_controller.rb
- app/helpers/activity_helper.rb
- app/models/conservation_record.rb
- app/models/cost_return_report.rb
- app/models/external_repair_record.rb
- app/models/in_house_repair_record.rb
- app/models/treatment_report.rb
- app/models/user.rb
- app/views/activity/index.html.erb
- app/views/activity/show.html.erb
- app/views/conservation_records/index.html.erb
- app/views/shared/_navigation.html.erb
- config/routes.rb
- db/migrate/20200131190904_create_versions.rb
- db/migrate/20200131192546_add_object_changes_to_versions.rb
- db/schema.rb
- spec/controllers/activity_controller_spec.rb
- spec/factories/activity.rb
- spec/helpers/activity_helper_spec.rb
- spec/rails_helper.rb
- spec/views/activity/index.html.erb
- spec/views/activity/show.html.erb
- spec/views/conservation_records/index.html.erb_spec.rb
DO NOT MERGE
Fixes #9 
This branch has been rebased.  Need to assess remaining working needed.
> paper trail

- .gitignore
- app/controllers/users_controller.rb
- app/models/ability.rb
- app/models/user.rb
- app/views/devise/shared/_links.html.erb
- app/views/shared/_navigation.html.erb
- app/views/users/index.html.erb
- app/views/users/new.html.erb
- config/routes.rb
- spec/controllers/users_controller_spec.rb
- spec/features/non_authenticated_user_spec.rb
- spec/spec_helper.rb
- spec/views/shared/_navigation.html.erb_spec.rb
- spec/views/users/index.html.erb_spec.rb
- spec/views/users/new.html.erb_spec.rb
> Add New Users

- Gemfile
- Gemfile.lock
- app/controllers/reports_controller.rb
- app/models/cost_return_report.rb
- app/models/report.rb
- app/views/reports/index.html.erb
- app/views/shared/_navigation.html.erb
- config/routes.rb
- db/schema.rb
- spec/controllers/reports_controller_spec.rb
- spec/factories/conservation_records.rb
- spec/factories/cost_return_reports.rb
- spec/views/reports/index.html.erb_spec.rb
- spec/views/shared/_navigation.html.erb_spec.rb
Resolves #78 
* Add ransack gem with config to index cost_return_reports with associated records
* Explicitly associate :cost_return_reports with :in_house_repair_records
* Add specs
> add workload access queries

- .github/workflows/upgrade-ruby.yml
Fixed issue with Ruby Upgrade GitHub Action not updating `Gemfile`.
> Fixed issue with Ruby Upgrade GitHub Action not updating `Gemfile`.

- app/controllers/users_controller.rb
- config/routes.rb
- spec/controllers/users_controller_spec.rb
- spec/helpers/abbreviated_treatment_report_helper_spec.rb
Resolves #122 
Add test for `generate_sum_minutes` in abbreviated_treatment_report_helper.
Add test for failed save on `#create_user` in users_controller
I discovered that we aren't using the users#show action, opting instead to default to :edit views for users, accessible only by authorized (admins). For this reason, I removed the show action from the users_controller and excluded it as a route. Willing to discuss.
> Increase test coverage

- app/models/ability.rb
- app/views/conservation_records/show.html.erb
- app/views/search/results.html.erb
- app/views/shared/_navigation.html.erb
- app/views/treatment_reports/_conservators_note_form.html.erb
- spec/controllers/conservation_records_controller_spec.rb
- spec/controllers/search_controller_spec.rb
- spec/features/end_to_end_spec.rb
- spec/features/non_authenticated_user_spec.rb
- spec/views/shared/_navigation.html.erb_spec.rb
Resolves #224 
Resolves #225 
Resolves #226 
Resolves #228
> UI changes

- spec/views/conservation_records/index.html.erb_spec.rb
> Remove hard-coded ids from spec

- spec/features/end_to_end_spec.rb
- spec/rails_helper.rb
Resolves #239 
Intermittent failure around object deletion seems to be related to running test suite in development rails env. Hard code rails env in test helper to solve.
> Hard code test env in test helper

- app/views/reports/index.html.erb
- spec/views/reports/index.html.erb_spec.rb
> report page UI changes

- app/controllers/conservation_records_controller.rb
- app/models/conservation_record.rb
- app/views/conservation_records/_conservation_record.json.jbuilder
- app/views/conservation_records/_form.html.erb
- app/views/conservation_records/abbreviated_treatment_report_pdf.html.erb
- app/views/conservation_records/conservation_worksheet.html.erb
- app/views/conservation_records/show.html.erb
- app/views/conservation_records/treatment_report_pdf.html.erb
- db/migrate/20211215190617_fix_conservation_record_column_name.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/batch.rake
- spec/controllers/conservation_records_controller_spec.rb
- spec/factories/conservation_records.rb
- spec/helpers/activity_helper_spec.rb
- spec/views/conservation_records/index.html.erb_spec.rb
- spec/views/conservation_records/show.html.erb_spec.rb
Resolves #256 
* add rake task for conservation record batch upload
* add migration to fix column name ConservationRecords column name :date_recei~~ie~~ved_in_preservation_services
Run rake task:
`rails batch:load:conservation_records CSV_LOCATION="/tmp/sample_batch_metadata.csv"`
> add batch upload for conservation records

- app/views/conservation_records/_form.html.erb
- app/views/treatment_reports/_form.html.erb
- spec/features/end_to_end_spec.rb
Fixes #267 
* Supply existing field value for form-selects (selected).
* Add spec to check edit views to make sure selected is displaying
> Supply value for selected on form selects

- Gemfile.lock
- lib/tasks/batch.rake
Format dates correctly when batch importing data.
> format dates correction in migration rake task

- lib/tasks/batch.rake
> fix migration field assignments

- Gemfile.lock
- app/helpers/conservation_records_helper.rb
- app/views/conservation_records/treatment_report_pdf.html.erb
- spec/helpers/conservation_records_helper_spec.rb
Resolves #318 
* Fix layout in pdf treatment report with some html tweaks.
> fix pdf layout

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
> Fix coveralls integration

- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- app/views/devise/shared/_links.html.erb
- app/views/shared/_navigation.html.erb
- spec/controllers/users/registrations_controller_spec.rb
- spec/views/shared/_navigation.html.erb_spec.rb
> Enable user self edit

- lib/tasks/batch.rake
> fix bug in treatment migration

- app/views/devise/registrations/edit.html.erb
#345 
Add bootstrap classes to user edit form.
> Add bootstrap style to user edit form

- Gemfile
- Gemfile.lock
- config/deploy/qa.rb
> Fix capistrano config

- Gemfile.lock
- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
> correct empty reports search 404

- Gemfile.lock
- app/views/conservation_records/conservation_worksheet.html.erb
Resolves #364 
[The Christians concordance_containing the most materiall words in the New Testament. By the helpe whereof he may (onely by calling to mind some one such word in a sentence) readily attaine to .pdf](https://github.com/uclibs/treatment_database/files/10561226/The.Christians.concordance_containing.the.most.materiall.words.in.the.New.Testament.By.the.helpe.whereof.he.may.onely.by.calling.to.mind.some.one.such.word.in.a.sentence.readily.attaine.to.pdf)
> Consolidate conservation worksheet to 1 page

- app/controllers/conservation_records_controller.rb
- spec/features/admin_user_spec.rb
- spec/features/end_to_end_spec.rb
> Desc order for conservation records index

- Gemfile.lock
> Add linux to bundle lock

- app/views/reports/index.html.erb
- spec/views/reports/index.html.erb_spec.rb
> Remove limit to records with repair

- app/assets/stylesheets/conservation_records.scss
- app/models/conservation_record.rb
- app/views/conservation_records/_form.html.erb
- spec/models/conservation_record_spec.rb
> Reduce conserv record validations

- app/controllers/treatment_reports_controller.rb
- app/views/conservation_records/abbreviated_treatment_report_pdf.html.erb
- app/views/conservation_records/show.html.erb
- app/views/treatment_reports/_abbreviated_treatment_report_form.html.erb
- db/migrate/20230224201755_rename_column_conservators_note.rb
- db/schema.rb
- spec/controllers/treatment_reports_controller_spec.rb
- spec/helpers/activity_helper_spec.rb
> Re-label conservators note to abbreviated treatment report

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/reports_controller.rb
- app/helpers/application_helper.rb
- app/helpers/external_repair_records_helper.rb
- app/helpers/in_house_repair_records_helper.rb
- app/jobs/data_export_job.rb
- app/models/ability.rb
- app/models/report.rb
- app/views/reports/index.html.erb
- config/application.rb
- config/routes.rb
- db/migrate/20230405164035_create_reports.rb
- db/migrate/20230405164303_create_active_storage_tables.active_storage.rb
- db/schema.rb
- lib/tasks/batch.rake
- lib/tasks/export.rake
- spec/controllers/reports_controller_spec.rb
- spec/factories/reports.rb
- spec/jobs/data_export_job_spec.rb
- spec/models/ability_spec.rb
- spec/models/report_spec.rb
- spec/tasks/export_spec.rb
- spec/views/reports/index.html.erb_spec.rb
- test/fixtures/files/test.csv
Resolves #79 
Export database to CSV.
> Add csv export

- Gemfile.lock
- app/views/conservation_records/abbreviated_treatment_report_pdf.html.erb
> Remove bold for abbreviated treatment report text

- .rubocop.yml
- app/helpers/conservation_records_helper.rb
- config/deploy.rb
- config/deploy/production.rb
> Add confirmation check during deploy

- app/views/conservation_records/abbreviated_treatment_report_pdf.html.erb
- app/views/conservation_records/treatment_report_pdf.html.erb
Resolves #422 
Change font-type to Times New Roman for Treatment Report and Abbreviated Treatment report. The worksheet pdf has a font change in #432
> Change typeface to times new roman

- .rubocop.yml
- scripts/add-data.rb
Resolves #417 
Commit add_data.rb to `/scripts` directory. This script was used to add missing abbreviate_treatment_report / conservator's note data.
> Add script for missing abbreviated_treatment_report data

- config/deploy.rb
> Expand deploy confirmation to accept variations of Y

- Gemfile
- Gemfile.lock
- app/assets/javascripts/abbreviated_treatment_report.coffee
- app/assets/javascripts/activity.coffee
- app/assets/javascripts/application.js
- app/assets/javascripts/con_tech_records.coffee
- app/assets/javascripts/conservation_records.coffee
- app/assets/javascripts/conservators_technicians.coffee
- app/assets/javascripts/controlled_vocabularies.coffee
- app/assets/javascripts/cost_return_report.coffee
- app/assets/javascripts/external_records.coffee
- app/assets/javascripts/front.coffee
- app/assets/javascripts/in_house_repair_records.coffee
- app/assets/javascripts/search.coffee
- app/assets/javascripts/staff_codes.coffee
- app/assets/javascripts/treatment_reports.coffee
- app/assets/javascripts/users.coffee
Fixes #456 
This PR removes the gem coffeescript-rails and the automatically-generated coffeescript files that have never been hooked up or used.  This is just general app clean-up.
> 456 - Remove Coffeescript

- Gemfile
- Gemfile.lock
> Add bigdecimal gem to Gemfile

- spec/features/end_to_end_spec.rb
- spec/features/specs/user_scenarios/admin_user_spec.rb
- spec/features/specs/user_scenarios/non_authenticated_user_spec.rb
- spec/features/specs/user_scenarios/read_only_user_spec.rb
- spec/features/specs/user_scenarios/standard_user_spec.rb
- spec/features/standard_user_spec.rb
- spec/features/support/shared_examples/record_editing/controlled_vocabulary_editing.rb
This PR pulls out the editing of controlled vocabularies and makes it modular.  It also checks that unauthorized users cannot access the editing page.
> MERGE TO FEATURE BRANCH - 214 Edit controlled vocabularies - MERGE FIRST

- CHANGELOG.md
Updated changelog to version 1.1.0 in preparation for production deployment Aug 8.
> LIBTREATDB-67 Update Changelog

- README.md
https://ucdts.atlassian.net/browse/LIBTREATDB-76
This PR updates the README.md file to include information about the accounts created with seeding the database.  It also includes reminder instructions to build the app properly before attempting testing.
> LIBTREATDB-76 Update readme to include information about user accounts
