uclibs/treatment_database

app/views/shared/_navigation.html.erb, spec/views/shared/_navigation.html.erb_spec.rb
The link to the Conservation Records page in the nav bar should be plural.
fixes: #28
=> Pluralizes the Conservation Records link in the navbar

app/views/conservation_records/conservation_worksheet.html.erb
Fixes: #33 
I had set the container height for the image as 100%, for what ever reason that was causing the image to be somewhat squished on lucy
=> #33 Remove height declaration causing the squash.

app/views/conservation_records/index.html.erb, app/views/conservation_records/show.html.erb, spec/views/conservation_records/index.html.erb_spec.rb, spec/views/conservation_records/show.html.erb_spec.rb
Fixes: #14 
Adds a column on the index page for Database ID.
Adds Database ID to the Conservation Records show page.
=> #14 Shows Database ID on Show and Index Page

app/views/conservation_records/show.html.erb
fixes: #32 
Before, if you landed on a conservation record page from a link on the main page the form wouldn't work without refreshing the page.  The div of the modal's body started before the form and ended with-in the form.  Something about this caused the button to be placed outside of the form tag.
I moved the div of the modal body into the form and it appears to be working well.
=> #32 Fix Repair Records Forms

app/views/shared/_navigation.html.erb, spec/views/shared/_navigation.html.erb_spec.rb
Resolves #56 
Display current user name in nav when logged in, drop-down menu items for edit and logout actions.
=> display current user in nav

.rubocop.yml, app/models/ability.rb, spec/controllers/conservation_records_controller_spec.rb
fixes #60 
We didn't have test coverage to ensure that both standard and admin users could download treatment reports and conservation worksheets, I read up on some of the CanCanCan documentation and have built out the tests a bit more.
=> #60 Allows standard users to download conservation worksheets and treatment reports

app/controllers/controlled_vocabularies_controller.rb, app/models/ability.rb, app/views/controlled_vocabularies/index.html.erb, config/routes.rb, spec/controllers/controlled_vocabularies_controller_spec.rb, spec/models/ability_spec.rb, spec/requests/controlled_vocabularies_spec.rb, spec/routing/controlled_vocabularies_routing_spec.rb, spec/views/shared/_navigation.html.erb_spec.rb
Fixes: #71
Fixes: #72 
Changes logic and test to only allow admins to add and edit controlled vocabularies.
Also, prevents the deletion of controlled vocabularies.
=> #71, #72 Only permit admins to add and edit controlled vocabularies

app/controllers/treatment_reports_controller.rb, app/views/conservation_records/show.html.erb, app/views/treatment_reports/_conservators_note_form.html.erb, app/views/treatment_reports/_form.html.erb, db/migrate/20200320134630_add_conservators_note_to_treatment_report.rb, db/schema.rb, spec/controllers/treatment_reports_controller_spec.rb
fixes #76 
This PR adds a form for the conservators note, I think the best way to do this is to add a field on the treatment report model.
Additionally, I moved treatment report related forms into partials, I think I should do this with the other elements on this page but should likely open a new issue for that kind of refactor.
I've started noticing that one of my specs in this project is failing because of a non-unique key error, this is addressed in another PR.  In the mean time running `rake db:reset` and then running the specs seems to work.
=> #76 Add Conservators Note

spec/rails_helper.rb, spec/views/conservation_records/index.html.erb_spec.rb
Resolves #150 
Ran `rspec --bisect` and revealed a line in the specs was clearing the database. When run in random order, this resulted in unreliable db state. Also added :request devise integation helper to rails_helper.rb
=> resolve failing specs

spec/views/conservation_records/index.html.erb_spec.rb
conservation_records#index view spec was throwing failure for unique constraint because we were creating a test record with set id before *each* example. Backed off to just once for all tests and this passes now.
=> fix uniq constraint failure in spec

lib/tasks/batch.rake
Correct typos in header keys for Treatment Report migration
Fixes #294 
Fixes #296 
Depends on [#295 ](https://github.com/uclibs/treatment_database/pull/295)
=> fix typos in Treatment Reports migration task

app/models/ability.rb, app/models/user.rb, app/views/shared/_navigation.html.erb, config/routes.rb, spec/controllers/users/registrations_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/views/shared/_navigation.html.erb_spec.rb
Resolves #319 
Remove :registerable module from devise to disable self-service signup and editing for user accounts. Users can still update their own passwords.
=> Disable signup/edit for non-admin users

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb, config/deploy/qa.rb, scripts/check_ruby.sh
- Pin Capistrano Version to 3.11.2
- Fix use of scripts in current (change to use from the latest pull)
- Update ruby check script to use the disable dtrace
- Change qa deploy to use qa branch by default
=> Capistrano fixes

app/models/treatment_report.rb, spec/features/end_to_end_spec.rb
Resolves #352 
Log only :update and :destroy actions for treatment-reports in paper_trail.
---
A TreatmentReport record with nil values is automatically created with a :before_action filter for ConservationRecords that don't have one attached. For ConservationRecords that were migrated without TreatmentReport data, any action on that record will create a TreatmentReport record and log the creation in the Activity Log.
Many of the Conservation Records do not have Treatment report records attached. The before_action filter to create and attach a Treatment Report is required by the form logic.
Change paper_trail config to stop logging TreatmentReport record create actions. This suppresses a less meaningful log message and cleans up the logs.
=> Stop logging treatment-record:create in paper_trail

app/controllers/conservation_records_controller.rb, spec/controllers/conservation_records_controller_spec.rb
Resolves #375 
Truncate titles to 25 characters before interpolating to PDF filenames.
=> Truncate pdf filenames

app/views/conservation_records/treatment_report_pdf.html.erb
Resolves #362
[A collection of 21 ledgers, binders and pamphlets from the cemetery_treatment_report-2.pdf](https://github.com/uclibs/treatment_database/files/10561065/A.collection.of.21.ledgers.binders.and.pamphlets.from.the.cemetery_treatment_report-2.pdf)
=> fix cutoff text in treatment pdf

app/controllers/activity_controller.rb, app/models/ability.rb, spec/models/ability_spec.rb
Resolves #408 
We use CanCan to authorize actions in the app and neglected to include the activity log in the abilities set. 
This PR restricts activity log access to standard and admin users using abilities model. 
Also fleshes out specs for admin abilities.
=> Restrict access to activity log

Gemfile.lock, config/application.rb, spec/controllers/activity_controller_spec.rb, spec/features/admin_user_spec.rb, spec/features/end_to_end_spec.rb, spec/rails_helper.rb
Resolves #410
`@version.changeset` was returning an empty hash due to YAML serialization permitted class exceptions, restrictions introduced after an RCE escalation risk was discovered. Examining the deserializer in the paper_trail gem showed that we needed to allow `ActiveSupport::TimeWithZone, Time, ActiveSupport::TimeZone` classes for the changes to load.
Debug here: https://github.com/paper-trail-gem/paper_trail/blob/master/lib/paper_trail/version_concern.rb#L357
Related: https://discuss.rubyonrails.org/t/cve-2022-32224-possible-rce-escalation-bug-with-serialized-columns-in-active-record/81017
And: https://stackoverflow.com/a/72970171
**Changes**
* Allow `ActiveSupport::TimeWithZone, Time, ActiveSupport::TimeZone` classes for yaml load in `config/application.rb`
* Add rspec helper …
=> Fix error preventing activity log diff

Gemfile.lock, app/models/con_tech_record.rb, config/application.rb, spec/models/con_tech_record_spec.rb, spec/models/conservation_record_spec.rb, spec/models/external_repair_record_spec.rb, spec/models/in_house_repair_record.rb, spec/models/treatment_report_spec.rb
Resolves #431 
Add conservators_and_technicians to version tracking. Also add line to model specs to make sure the object is being tracked in versioning.
=> Add conservators and technicians to version tracking

app/controllers/search_controller.rb, spec/controllers/search_controller_spec.rb
Resolves #418 
The search controller was using a restrictive regex to identify item record numbers in search strings, looking for precise pattern of a string initilized by a single lower-case "i", followed by a series of numeric characters. Not all records have these item-record numbers: those without are assigned an identifier initialized with 'notcat' and a series of numeric characters. Staff expected the "notcat" identifiers to be retrievable via search but results excluded these records. 
To fix, we edit the regex patter for item-record retrieval to include any initial alpha character series followed by digits. This will return results with identifiers initialized with "i", "notcat" and any other series of alpha characters followed by numeric characters.
=> Include uncataloged id's in item record search

app/controllers/con_tech_records_controller.rb, app/controllers/cost_return_reports_controller.rb, app/controllers/external_repair_records_controller.rb, app/controllers/in_house_repair_records_controller.rb, app/controllers/treatment_reports_controller.rb, app/views/conservation_records/show.html.erb, spec/controllers/con_tech_records_controller_spec.rb, spec/controllers/cost_return_reports_controller_spec.rb, spec/controllers/external_repair_records_controller_spec.rb, spec/controllers/in_house_repair_records_controller_spec.rb, spec/controllers/treatment_reports_controller_spec.rb
Resolves #420 
Workaround to help preserve scroll position while editing objects in combined show view/form. 
* Add anchors to section headers
* Embed anchors in controller redirects for all appropriate actions
* In the controller specs, add checks for anchors in the redirects
=> Add anchors and redirect embeds to help preserve scroll position

app/controllers/conservation_records_controller.rb, app/controllers/controlled_vocabularies_controller.rb, app/views/controlled_vocabularies/_controlled_vocabulary.json.jbuilder, app/views/controlled_vocabularies/_form.html.erb, app/views/controlled_vocabularies/index.html.erb, app/views/controlled_vocabularies/show.html.erb, db/migrate/20240307145522_add_favorite_to_controlled_vocabulary.rb, db/schema.rb, spec/controllers/conservation_records_controller_spec.rb, spec/controllers/controlled_vocabularies_controller_spec.rb, spec/features/end_to_end_spec.rb, spec/views/controlled_vocabularies/edit.html.erb_spec.rb, spec/views/controlled_vocabularies/index.html.erb_spec.rb, spec/views/controlled_vocabularies/new.html.erb_spec.rb, spec/views/controlled_vocabularies/show.html.erb_spec.rb
Resolves #428 
Add favorite:boolean variable to the ControlledVocabulary object along with view components to edit and display. Add sort to @repair_type which feeds the Repair Type form drop-downs, so that vocab terms marked as favorite will sort to top of select options.
This allows admin to choose repair type terms that should sort to top of options. The sort has only been applied to repair types but could be applied to other controlled vocab select menus. 
I should note that in the issue, preservation staff requested a specific order for repair types. I think this is a compromise that allows them to control priority of the terms without the rigidity of hard-coding the order. The trade-off is a lack of precision. 
We should check with Preservation staff to confirm if this solution is …
=> Add favorite:boolean to controlled vocab

README.md
Resolves #351 
* Add deploy instructions to README for QA and Prod. 
* Remove outdated information about pdf generation tools.
=> Add deploy instructions to README

app/views/conservation_records/treatment_report_pdf.html.erb, spec/views/conservation_records/treatment_report_pdf.erb_spec.rb
Resolves #430 
Conservators and technicians were missing from the full treatment report. Add them with a spec. 
Ex: [Farewell to Arms_treatment_report.pdf](https://github.com/uclibs/treatment_database/files/14937256/Farewell.to.Arms_treatment_report.pdf)
=> Add conservators & technicians to full treatment report

Gemfile, Gemfile.lock, spec/features/specs/user_scenarios/admin_user_spec.rb, spec/features/specs/user_scenarios/read_only_user_spec.rb, spec/features/specs/user_scenarios/standard_user_spec.rb, spec/features/support/helpers/authentication_helpers.rb, spec/features/support/helpers/pdf_download_helpers.rb, spec/features/support/shared_contexts/admin_user_context.rb, spec/features/support/shared_contexts/read_only_user_context.rb, spec/features/support/shared_contexts/standard_user_context.rb
Ref #214 
This pull request introduces shared contexts that utilize authentication_helpers to log in users for tests in features/specs/user_scenarios. These contexts standardize user authentication across specs, enhancing test reliability and reducing code redundancy.
- Gemfile
- Add "launchy" gem to make it easier to visualize feature tests mid-test
- spec/features/specs/user_scenarios/admin_user_spec.rb
- Add admin context and a passing test
- spec/features/specs/user_scenarios/read_only_user_spec.rb
- Add read_only context and a passing test   
- spec/features/specs/user_scenarios/standard_user_spec.rb
- Add standard user context and a passing test
- spec/features/support/helpers/authentication_helpers.rb
- created login helper and verification functions for it
- …
=> MERGE TO FEATURE BRANCH - 214 - Use Context for Login - MERGE FIRST

app/models/ability.rb, lib/tasks/export.rake, spec/controllers/reports_controller_spec.rb, spec/models/ability_spec.rb, spec/views/conservation_records/index.html.erb_spec.rb
Fixes #479 
We didn't intend to give standard users access to the reports and activity pages.  This PR revokes those permissions, updating tests to match the new permissions.
spec/views/conservation_records/index.html.erb_spec.rb was modified because it was failing pagination checks.
=> 479 restrict standard user views

app/controllers/staff_codes_controller.rb, app/controllers/users/registrations_controller.rb, app/models/ability.rb, app/views/shared/_navigation.html.erb, app/views/staff_codes/index.html.erb, config/environments/test.rb, config/initializers/devise.rb, config/routes.rb, spec/controllers/staff_codes_controller_spec.rb, spec/features/admin_user_spec.rb, spec/features/standard_user_spec.rb, spec/helpers/in_house_repair_records_helper_spec.rb, spec/mailers/application_mailer_spec.rb, spec/mailers/devise_mailer_spec.rb, spec/models/ability_spec.rb, spec/requests/staff_codes_spec.rb, spec/routing/staff_codes_routing_spec.rb
We had no link on the admin header for staff codes, and standard users were able to access this page.
This PR corrects these two errors, adding a link in the admin header and removing access for the standard users.
Additionally, we are removing the ability for any user to delete or destroy a staff code.  If the preservation team needs to remove a staff code in the future, we will need to do it for them.
File changes:
- app/controllers/staff_codes_controller.rb
- remove delete method 
- app/models/ability.rb
- removes standard user access to staff codes
- removes admin ability to delete staff codes
- app/views/shared/_navigation.html.erb
- adds link for staff codes to permitted users (admin-only)
- app/views/staff_codes/index.html.erb
- remove links to destroy staff codes
- …
=> 482 - Correct staff codes access

app/views/treatment_reports/_abbreviated_treatment_report_form.html.erb, app/views/treatment_reports/_form.html.erb, spec/features/end_to_end_spec.rb, spec/features/specs/user_scenarios/read_only_user_spec.rb, spec/features/support/shared_examples/read_only_checks/read_only_cons_record_check.rb
We have some specific css and link/button visibility with read-only users.  This PR looks at the read-only user's perspective when looking at both the index page and a conservation record, and makes sure that it is only showing the links it should.  Read only users should not have links to create or edit conservation records, or to add new repairs or technicians.  They should have disabled input fields for the treatment report fields.
Other Changes
- app/views/treatment_reports/_abbreviated_treatment_report_form.html.erb - removed blank line
- app/views/treatment_reports/_form.html.erb - corrected form indentation.  Did not change form.
- spec/features/end_to_end_spec.rb - corrected duplicated code
=> MERGE TO FEATURE - 214 Read only conservation record checks - MERGE FIRST

Gemfile, Gemfile.lock
This PR adds the gems we expect to need to use while making the change to SSO.
We do not expect to need 'omniauth-openid' because we are integrating directly with Shibboleth and validating against a set list of approved users.  We do not allow any other time of login or account creation.
=> FEATURE MERGE - 407 add gems

Gemfile, Gemfile.lock
Resolves #496 
Recent release of wkhtmltopdf_binary gem includes fix to accommodate oracle linux. We created a forked repo with PR to the parent that was accepted in most recent release, we can now decommission our fork.
=> Decommission wkhtmltopdf_binary fork

Gemfile, Gemfile.lock
Fixes #513 
Upon running "bundle install", we were getting an error message for the end of life for the gem `ruby-sass`.  
We weren't actually using `ruby-sass` directly, but our gem `sass-rails` was.  This warning was fixed in version 6.0.0 of `sass-rails`. (See https://github.com/rails/sass-rails/issues/435)
I updated our Gemfile from asking for `sass-rails (~> 5.0)` to asking for `sass-rails (~> 6.0)`.  Local testing has the app still working the same way, and our tests are still passing.
=> 513 - Upgrade sass-rails from ~>5.0 to ~>6.0

spec/rails_helper.rb, spec/support/shared_contexts/rake.rb
Fixes #519 
This PR adds a shared context for the testing of Rake tasks, indicated in Rspec by `type :task`.  It loads the rake tasks we have, both custom and built-in, and then clears the Rake application after each test to help keep changes made in one test from affecting other tests.  These steps could be manually done in each test; this PR is to help keep code DRY and to assist in keeping rake tests from affecting the state of other rake tests.
=> 519 - Add shared rake test context

db/seeds.rb
Modifies the db/seeds.rb file to add in Staff Codes when the command `rails db:seed` is run.  The codes match the codes currently used in production.
To test:
`rails db:drop`
`rails db:create`
`rails db:migrate`
`rails db:seed`
Log in as admin with email 'chuck@chuck.codes' and password 'notapass'
Go to the main conservation records index page.  You should see exactly three records.
Go to /staff_codes (you will need to manually type this address in - there are no links)
You should see the following:
=> 524 - Add Staff Codes to seeds

config/deploy/production.rb
We couldn't deploy to libapps (production) but we could deploy to libappstest (qa).  These changes mimic the setup in libappstest (qa) and allowed us to deploy this branch to libapps (production).
=> HOLD FOR BOOTSTRAP UPDATE - Update config/deploy/production.rb to match qa.rb's setup

spec/features/end_to_end_spec.rb, spec/features/read_only_user_spec.rb, spec/support/capybara.rb
This PR takes the multiple initialization of Capybara drivers in several feature tests and puts it into a single support file.  This increases how DRY the code is and slightly improves efficiency as the drivers only need to be initialized once.
It also adds a default screen size for testing, to reduce confusion when testing responsive layouts.  I added this to the PR to make this PR able to be merged in any order with the pr's labeled "review anytime"
=> LIBTREATDB-72 Pull Capybara initialization code into support file for DRY code

spec/features/end_to_end_spec.rb, spec/features/read_only_user_spec.rb, spec/rails_helper.rb, spec/support/download_link_helper.rb
Our end-to-end and user-specific feature tests should have js: true in their metadata but currently don’t.  This is causing some tests to pass when they shouldn’t.
This pr adds js: true to the feature tests and corrects failing tests.
It introduces a helper module for checking that the “Download” links function as expected.  The expected behavior for these links is that they open up a new tab with a PDF of the requested report.  Limitations of Capybara prevent us from reading these new pages.  Instead, we temporarily disable the target: _blank property and check that the page displayed has the appropriate URL before returning to the original page.
=> LIBTREATDB-75 Correct feature tests to use js: true

app/javascript/application.js, app/javascript/custom/account_active_toggle_switch.js, app/views/users/_form.html.erb, spec/features/account_active_slider.rb, spec/requests/users_spec.rb
https://ucdts.atlassian.net/browse/LIBTREATDB-74
This is a cosmetic upgrade for the admin user.  To mark a user as active or not, previously we had a checkbox.  Now, with the adoption of Bootstrap 5, we have the option of using a slider which is more intuitive for this case.
This PR changes the "Active" checkbox to a slider that will display either "Account Active" or "Account Inactive" depending on the state of the slider.
If the slider is not changing the Account Active/Inactive status, you probably need to run `yarn install` and `yarn build`.  Then, clear the cache and reload the page.
=> LIBTREATDB-74 Update user active checkbox to a slider

db/seeds.rb, spec/seeds/seeds_spec.rb
[Jira Issue](https://github.com/uclibs/treatment_database/pull/555)
We had issues with the tests for checking if the environment variable "SEEDABLE".  They were flaky and failing sporadically.  Additionally, the database seeding file was printing the status of the seedable variable with every test run.  
This PR revamps the SEEDABLE tests to more accurately load and manage the testing environment.  It also makes the printing statements conditional on the Rails environment.
=> LIBTREATDB-87 Fix seedable tests

app/controllers/admin/users_controller.rb, app/views/admin/users/_edit_form.html.erb, spec/controllers/admin_users_controller_spec.rb, spec/features/admin_user_spec.rb, spec/features/end_to_end_spec.rb
Link: https://ucdts.atlassian.net/browse/LIBTREATDB-99
This PR takes away the ability of admins to update or change a user's email once it is set.  If an admin makes an error in the user creation phase and needs to use a different email, they will need to create a new user.  It gray's out the email section in a form and ignores any `params[:email]` sent to #update.  The only things an admin can change are display name, role, and active_status.
=> LIBTREATDB-99 admins should not be able to change email for sso

.github/workflows/update-pr.yml
Jira Issue: [LIBTREATDB-102](https://ucdts.atlassian.net/browse/LIBTREATDB-102)
This PR adds a configuration file for Github so that it will automatically run the shared action jira-pr-updater-action when a PR is created or edited.
=> LIBTREATDB-102 Add configuration to run github workflow jira-pr-updater-action
